# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from recommendation.v1 import recommendation_pb2 as recommendation_dot_v1_dot_recommendation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommendation/v1/recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventIngestionServiceStub(object):
    """============================================================================
    Event Ingestion Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvent = channel.unary_unary(
                '/recommendation.v1.EventIngestionService/IngestEvent',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.IngestEventRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.IngestEventResponse.FromString,
                _registered_method=True)
        self.IngestBatch = channel.unary_unary(
                '/recommendation.v1.EventIngestionService/IngestBatch',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.IngestBatchRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.IngestBatchResponse.FromString,
                _registered_method=True)


class EventIngestionServiceServicer(object):
    """============================================================================
    Event Ingestion Service
    ============================================================================

    """

    def IngestEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestEvent,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.IngestEventRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.IngestEventResponse.SerializeToString,
            ),
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.IngestBatchRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.IngestBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.EventIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.EventIngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventIngestionService(object):
    """============================================================================
    Event Ingestion Service
    ============================================================================

    """

    @staticmethod
    def IngestEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.EventIngestionService/IngestEvent',
            recommendation_dot_v1_dot_recommendation__pb2.IngestEventRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.IngestEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.EventIngestionService/IngestBatch',
            recommendation_dot_v1_dot_recommendation__pb2.IngestBatchRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.IngestBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FeatureServiceStub(object):
    """============================================================================
    Feature Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserFeatures = channel.unary_unary(
                '/recommendation.v1.FeatureService/GetUserFeatures',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetUserFeaturesRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
                _registered_method=True)
        self.GetItemFeatures = channel.unary_unary(
                '/recommendation.v1.FeatureService/GetItemFeatures',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetItemFeaturesRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
                _registered_method=True)
        self.GetBatchItemFeatures = channel.unary_unary(
                '/recommendation.v1.FeatureService/GetBatchItemFeatures',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetBatchItemFeaturesRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.BatchFeatureVector.FromString,
                _registered_method=True)
        self.GetCrossFeatures = channel.unary_unary(
                '/recommendation.v1.FeatureService/GetCrossFeatures',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetCrossFeaturesRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
                _registered_method=True)


class FeatureServiceServicer(object):
    """============================================================================
    Feature Service
    ============================================================================

    """

    def GetUserFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchItemFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFeatures,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetUserFeaturesRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.SerializeToString,
            ),
            'GetItemFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemFeatures,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetItemFeaturesRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.SerializeToString,
            ),
            'GetBatchItemFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchItemFeatures,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetBatchItemFeaturesRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.BatchFeatureVector.SerializeToString,
            ),
            'GetCrossFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossFeatures,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetCrossFeaturesRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.FeatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureService(object):
    """============================================================================
    Feature Service
    ============================================================================

    """

    @staticmethod
    def GetUserFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.FeatureService/GetUserFeatures',
            recommendation_dot_v1_dot_recommendation__pb2.GetUserFeaturesRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.FeatureService/GetItemFeatures',
            recommendation_dot_v1_dot_recommendation__pb2.GetItemFeaturesRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchItemFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.FeatureService/GetBatchItemFeatures',
            recommendation_dot_v1_dot_recommendation__pb2.GetBatchItemFeaturesRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.BatchFeatureVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCrossFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.FeatureService/GetCrossFeatures',
            recommendation_dot_v1_dot_recommendation__pb2.GetCrossFeaturesRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.FeatureVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RetrievalServiceStub(object):
    """============================================================================
    Retrieval Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveCandidates = channel.unary_unary(
                '/recommendation.v1.RetrievalService/RetrieveCandidates',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.CandidateSet.FromString,
                _registered_method=True)


class RetrievalServiceServicer(object):
    """============================================================================
    Retrieval Service
    ============================================================================

    """

    def RetrieveCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveCandidates,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.RetrievalRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.CandidateSet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """============================================================================
    Retrieval Service
    ============================================================================

    """

    @staticmethod
    def RetrieveCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RetrievalService/RetrieveCandidates',
            recommendation_dot_v1_dot_recommendation__pb2.RetrievalRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.CandidateSet.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RankingServiceStub(object):
    """============================================================================
    Ranking Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RankCandidates = channel.unary_unary(
                '/recommendation.v1.RankingService/RankCandidates',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.RankingRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.RankedResult.FromString,
                _registered_method=True)


class RankingServiceServicer(object):
    """============================================================================
    Ranking Service
    ============================================================================

    """

    def RankCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RankCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.RankCandidates,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.RankingRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.RankedResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.RankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.RankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RankingService(object):
    """============================================================================
    Ranking Service
    ============================================================================

    """

    @staticmethod
    def RankCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RankingService/RankCandidates',
            recommendation_dot_v1_dot_recommendation__pb2.RankingRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.RankedResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReRankingServiceStub(object):
    """============================================================================
    Re-Ranking Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReRank = channel.unary_unary(
                '/recommendation.v1.ReRankingService/ReRank',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.ReRankRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.ReRankedResult.FromString,
                _registered_method=True)


class ReRankingServiceServicer(object):
    """============================================================================
    Re-Ranking Service
    ============================================================================

    """

    def ReRank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReRankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReRank': grpc.unary_unary_rpc_method_handler(
                    servicer.ReRank,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.ReRankRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.ReRankedResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.ReRankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.ReRankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReRankingService(object):
    """============================================================================
    Re-Ranking Service
    ============================================================================

    """

    @staticmethod
    def ReRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.ReRankingService/ReRank',
            recommendation_dot_v1_dot_recommendation__pb2.ReRankRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.ReRankedResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecommendationServiceStub(object):
    """============================================================================
    Recommendation Service (External-Facing)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetRecommendations',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetSimilarItems = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetSimilarItems',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetSimilarItemsRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetPersonalizedFeed = channel.unary_unary(
                '/recommendation.v1.RecommendationService/GetPersonalizedFeed',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetFeedRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetFeedResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """============================================================================
    Recommendation Service (External-Facing)
    ============================================================================

    """

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimilarItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPersonalizedFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'GetSimilarItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimilarItems,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetSimilarItemsRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'GetPersonalizedFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPersonalizedFeed,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetFeedRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetFeedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """============================================================================
    Recommendation Service (External-Facing)
    ============================================================================

    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetRecommendations',
            recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSimilarItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetSimilarItems',
            recommendation_dot_v1_dot_recommendation__pb2.GetSimilarItemsRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPersonalizedFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.RecommendationService/GetPersonalizedFeed',
            recommendation_dot_v1_dot_recommendation__pb2.GetFeedRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.GetFeedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ExperimentationServiceStub(object):
    """============================================================================
    Experimentation Service
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAssignment = channel.unary_unary(
                '/recommendation.v1.ExperimentationService/GetAssignment',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.GetAssignmentRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.Assignment.FromString,
                _registered_method=True)
        self.LogExposure = channel.unary_unary(
                '/recommendation.v1.ExperimentationService/LogExposure',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.LogExposureRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.LogExposureResponse.FromString,
                _registered_method=True)


class ExperimentationServiceServicer(object):
    """============================================================================
    Experimentation Service
    ============================================================================

    """

    def GetAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogExposure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExperimentationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssignment,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.GetAssignmentRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.Assignment.SerializeToString,
            ),
            'LogExposure': grpc.unary_unary_rpc_method_handler(
                    servicer.LogExposure,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.LogExposureRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.LogExposureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.ExperimentationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.ExperimentationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExperimentationService(object):
    """============================================================================
    Experimentation Service
    ============================================================================

    """

    @staticmethod
    def GetAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.ExperimentationService/GetAssignment',
            recommendation_dot_v1_dot_recommendation__pb2.GetAssignmentRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.Assignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogExposure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.ExperimentationService/LogExposure',
            recommendation_dot_v1_dot_recommendation__pb2.LogExposureRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.LogExposureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """============================================================================
    Health Check (Standard gRPC Health)
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/recommendation.v1.HealthService/Check',
                request_serializer=recommendation_dot_v1_dot_recommendation__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommendation_dot_v1_dot_recommendation__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """============================================================================
    Health Check (Standard gRPC Health)
    ============================================================================

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=recommendation_dot_v1_dot_recommendation__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommendation_dot_v1_dot_recommendation__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """============================================================================
    Health Check (Standard gRPC Health)
    ============================================================================

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.v1.HealthService/Check',
            recommendation_dot_v1_dot_recommendation__pb2.HealthCheckRequest.SerializeToString,
            recommendation_dot_v1_dot_recommendation__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
